name: Tag
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-tag:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Tag Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ github.head_ref }}
          git push --tags origin
